# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - pre
  - build
  - test
  - report
  - deploy
  - publish

variables:
  MIRROR_REPO: "https://simbarras:$GITHUB_PASSWORD@github.com/simbarras/tb23-gpu-opt-celeritas.git"

include:
  - template: Security/SAST.gitlab-ci.yml
  - local: /ci/template.gitlab-ci.yml

update-mirror:
  stage: pre
  image: alpine:latest
  script:
    - apk add --no-cache git
    # Pushing to the mirror repo on GitHub
    - git push --mirror $MIRROR_REPO
sast:
  stage: test



# DOCUMENTATION

compile-specification-pdf:
  extends: .compile_pdf
  variables:
    FILE: specification

compile-report-pdf:
  extends: .compile_pdf
  variables:
    FILE: report

pages:
  only:
    - main
  stage: publish
  image: alpine:latest
  script:
    - mkdir -p "public"
    # Add/update specification
    - cp doc/specification.pdf public/Spec_TB_2223_GPU-OPT.pdf  # copy the pdf file into the public folder
    - cp doc/specification.svg public/specification.svg  # copy the pdf file into the public folder
    # Add/update report
    - cp doc/report.pdf public/Report_TB_2223_GPU-OPT.pdf  # copy the pdf file into the public folder
    - cp doc/report.svg public/report.svg  # copy the pdf file into the public folder
  artifacts:
    paths:
      - public  # instruct GitLab to keep the public folder