on:
  push:

env:
  GITLAB_PROJECT_ID: 15080

name: Update Mirror

jobs:
  update-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Git
        run: sudo apt-get update && sudo apt-get install -y git
      - name: Add mirror remote
        run: git remote add mirror https://simon.barras:${{ secrets.GITLAB_TOKEN }}@gitlab.forge.hefr.ch/frederic.bapst/tb23-gpu-opt-celeritas.git
      - name: Unshallow
        run: git fetch --unshallow
      - name: Push to mirror
        run: git push mirror $(basename ${{ github.ref }}) --force

  wait-mirror-pipeline:
    runs-on: ubuntu-latest
    needs: update-mirror
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install curl and jq
        run: sudo apt-get update && sudo apt-get install -y curl jq
      - name: Add execute permission to wait_gitlab.sh
        run: chmod +x ci/wait_gitlab.sh
      - name: Wait for mirror pipeline to finish
        run: ci/wait_gitlab.sh ${{ secrets.GITLAB_TOKEN}} ${{ env.GITLAB_PROJECT_ID }} $(basename ${{ github.ref }})
